name: Simple CI With github

on: push

jobs:
  job_1:
    name: Run Integration Test
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: "14"
        - run: npm install
        - run: npm test
