name: example-basic
on:
  push:
    branches:
      - "master"
  pull_request:
jobs:
  # note: Ubuntu 16 probably works, but is deprecated

  basic-ubuntu-18:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        uses: actions/setup-node@v2
          - node-version: '16'
    run: npm test      